version: '3.4'

services:
  pxlidcardv2.api:
    image: ${DOCKER_REGISTRY-}pxlidcardv2api
    build:
      context: .
      dockerfile: PXLIDCardV2.api/Dockerfile
    depends_on:
      - sqldata


  sqldata:
    image: mcr.microsoft.com/mssql/server:2019-latest
