// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PXLIDCardV2.data;

namespace PXLIDCardV2.data.Migrations
{
    [DbContext(typeof(Context))]
    partial class ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.12")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("PXLIDCardV2.domain.Evaluations.Course", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.ToTable("Courses");

                    b.HasData(
                        new
                        {
                            Id = 5000,
                            Name = ".NET Expert"
                        },
                        new
                        {
                            Id = 5001,
                            Name = "Java Expert"
                        });
                });

            modelBuilder.Entity("PXLIDCardV2.domain.Evaluations.Evaluation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<int>("EvaluationType")
                        .HasColumnType("int");

                    b.Property<int>("LectorId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.HasIndex("LectorId");

                    b.ToTable("Evaluations");

                    b.HasData(
                        new
                        {
                            Id = 6000,
                            CourseId = 5000,
                            EvaluationType = 0,
                            LectorId = 2000
                        },
                        new
                        {
                            Id = 6001,
                            CourseId = 5001,
                            EvaluationType = 1,
                            LectorId = 2001
                        });
                });

            modelBuilder.Entity("PXLIDCardV2.domain.StudentEvaluation", b =>
                {
                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<int>("EvaluationId")
                        .HasColumnType("int");

                    b.Property<bool>("HasAttended")
                        .HasColumnType("bit");

                    b.HasKey("StudentId", "EvaluationId");

                    b.HasIndex("EvaluationId");

                    b.ToTable("StudentEvaluations");

                    b.HasData(
                        new
                        {
                            StudentId = 1000,
                            EvaluationId = 6000,
                            HasAttended = false
                        },
                        new
                        {
                            StudentId = 1000,
                            EvaluationId = 6001,
                            HasAttended = false
                        },
                        new
                        {
                            StudentId = 1001,
                            EvaluationId = 6000,
                            HasAttended = false
                        });
                });

            modelBuilder.Entity("PXLIDCardV2.domain.Users.Admin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Admins");

                    b.HasData(
                        new
                        {
                            Id = 3000,
                            Email = "john.doe@admin.pxl.be",
                            FirstName = "John",
                            LastName = "Doe",
                            Password = "123456"
                        },
                        new
                        {
                            Id = 3001,
                            Email = "jane.doe@admin.pxl.be",
                            FirstName = "Jane",
                            LastName = "Doe",
                            Password = "123456"
                        });
                });

            modelBuilder.Entity("PXLIDCardV2.domain.Users.Lector", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Lectors");

                    b.HasData(
                        new
                        {
                            Id = 2000,
                            Email = "kris.hermans@lector.pxl.be",
                            FirstName = "Kris",
                            LastName = "Hermans",
                            Password = "123456"
                        },
                        new
                        {
                            Id = 2001,
                            Email = "tom.schuyten@lector.pxl.be",
                            FirstName = "Tom",
                            LastName = "Schuyten",
                            Password = "123456"
                        });
                });

            modelBuilder.Entity("PXLIDCardV2.domain.Users.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            Id = 1000,
                            Email = "jeff.willen@student.pxl.be",
                            FirstName = "Jeff",
                            LastName = "Willen",
                            Password = "123456"
                        },
                        new
                        {
                            Id = 1001,
                            Email = "sigrid.meesters@student.pxl.be",
                            FirstName = "Sigrid",
                            LastName = "Meesters",
                            Password = "123456"
                        });
                });

            modelBuilder.Entity("PXLIDCardV2.domain.Evaluations.Evaluation", b =>
                {
                    b.HasOne("PXLIDCardV2.domain.Evaluations.Course", null)
                        .WithMany("Evaluations")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PXLIDCardV2.domain.Users.Lector", null)
                        .WithMany("LectorEvaluations")
                        .HasForeignKey("LectorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PXLIDCardV2.domain.StudentEvaluation", b =>
                {
                    b.HasOne("PXLIDCardV2.domain.Evaluations.Evaluation", "Evaluation")
                        .WithMany("StudentEvaluations")
                        .HasForeignKey("EvaluationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PXLIDCardV2.domain.Users.Student", "Student")
                        .WithMany("StudentEvaluations")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Evaluation");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("PXLIDCardV2.domain.Evaluations.Course", b =>
                {
                    b.Navigation("Evaluations");
                });

            modelBuilder.Entity("PXLIDCardV2.domain.Evaluations.Evaluation", b =>
                {
                    b.Navigation("StudentEvaluations");
                });

            modelBuilder.Entity("PXLIDCardV2.domain.Users.Lector", b =>
                {
                    b.Navigation("LectorEvaluations");
                });

            modelBuilder.Entity("PXLIDCardV2.domain.Users.Student", b =>
                {
                    b.Navigation("StudentEvaluations");
                });
#pragma warning restore 612, 618
        }
    }
}
